### ISSUE TITLE
Maven issue

### ISSUE THREAD

**Issue by ccristian** [berndruecker/flowing-retail#4]
When i run mvn install as described in the readme i get the following

Downloading: https://app.camunda.com/nexus/content/groups/public/org/camunda/camunda-release-parent/2.5/camunda-release-parent-2.5.pom
Downloaded: https://app.camunda.com/nexus/content/groups/public/org/camunda/camunda-release-parent/2.5/camunda-release-parent-2.5.pom (13 KB at 108.2 KB/sec)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.camunda.bpm:camunda-bom:pom:7.7.3-ee in camunda-bpm-nexus (https://app.camunda.com/nexus/content/groups/public) @ line 20, column 16
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   

Thanks

**Comment by ccristian** [comment]
Tried 7.7.0 worked until next error when it needs 7.7.2-ee that does not exist and the saga continues

**Comment by ccristian** [comment]
removed the provide 7.7.2-ee dependencies went further 
Running from maven the main failed, but it workd from intelliJ 👍 
starting the first services checkout ,inventory and monitoring...worked
failed on OrderApplication :(

2017-11-12 17:10:53.719  WARN 6691 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lazyInitRegistration' defined in class path resource [org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.RuntimeException: javax.servlet.ServletException: Could not read security filter config file '/securityFilterRules.json': no such resource in servlet context.

**Comment by ccristian** [comment]
If you have time please take a look as for the moment I am stuck.
Would be nice to have a working version out of the box. (even without automatic topic creation)
Let me know please how can I help.
Regards
Cristian

**Comment by berndruecker** [comment]
Should be fixed with https://github.com/flowing/flowing-retail/commit/8af6e6bb0497817ac2a0498e5a71d06572e4a5f8 - works fine locally for me. Can you confirm?

**Comment by kanguran** [comment]
I have such code to init Camunda beans, it work well on Camunda  7.9-EE, Springboot starter 3.0 and StringBoot 2.0.2.

@Component
public class ScriptingEngineInitializer implements ApplicationContextAware {

    @Autowired
    private ProcessEngine processEngine;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        ProcessEngineConfigurationImpl config = (ProcessEngineConfigurationImpl)processEngine.getProcessEngineConfiguration();
        final Map<Object, Object > beans = config.getBeans();
        Arrays.asList(applicationContext.getBeanDefinitionNames()).forEach(beanName -> {
            beans.putIfAbsent(beanName, applicationContext.getBean(beanName));
        });

    }
}

On upgrade to  Camunda  7.10-EE, Springboot starter 3.2 and StringBoot 2.1.1.
I am getting similar error:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scriptingEngineInitializer' defined in file [C:\Mycode\target\classes\com\engine\scripting\ScriptingEngineInitializer.class]:
 Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lazyInitRegistration' defined in class path resource 
 [org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.RuntimeException: javax.servlet.ServletException: 
 Could not read security filter config file '/securityFilterRules.json': no such resource in servlet context.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:584)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)`

Similar error comes on Camunda 7.11-ee aswell, because of the fact that XML libraries are moved outside Spring boot in 2.1 releases.

Using this external dependancy because of new Spring boot.
`        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.0</version>
        </dependency>`

Any ideas how to overcome the same issue on latest Camunda versions running on Spring boot 2.1.X
